services:
  - type: web
    name: veyro
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB
        sync: false
      - key: MONGODB_DB_NAME
        value: Veyro
      - key: OWNER_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: LOGGER_GROUP
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        value: main
      - key: RENDER_DEPLOY_HOOK
        sync: false
